version: "3"

services:
  proxy-kcptun-client:
    image: proxy-kcptun:latest
    command: >-
      client
      -r "127.0.0.1:4000"
      -l ":8388"
      -mode fast3
      -nocomp
      -autoexpire 900
      -sockbuf 16777217
      -dscp 46
    expose:
      - 8338/udp
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge