version: "3"

services:
  proxy-shadowsocks-client:
    image: proxy-ss:latest
    command: >-
        ss-local 
        -s 127.0.0.1
        -p 8338
        -b 0.0.0.0
        -l 8443
        -k 123456
        -m aes-256-gcm
        -u
    ports:
      - "8443:8443/tcp"
      - "8443:8443/udp"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge