version: "3"

services:
  proxy-udpspeederv2-client:
    image: proxy-udpspeederv2:latest
    command: >-
        -c
        -l0.0.0.0:6500
        -r127.0.0.1:3334
        -f1:3,2:4,8:6,20:10
        -k 123456
    ports:
      - "6500:6500/udp"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge